[alembic]
script_location = migrations
prepend_sys_path = .
sqlalchemy.url = mysql+pymysql://root:1093219367@localhost/alojamientos_db

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic